[start_message]

hello_msg = """
Здравствуйте! 👋

Добро пожаловать в наш телеграм-бот! Мы рады, что вы присоединились к нам. Здесь вы найдёте полезную информацию и сможете быстро получить ответы на свои вопросы.

Если у вас возникнут какие-либо проблемы или предложения, пожалуйста, не стесняйтесь обращаться к нам. Мы всегда готовы помочь!

Желаем вам приятного использования нашего бота! 😊

"""


[questions]

question1 = '''<em>Что выведет данный код:</em>
if 5 :
    print('Да')
else:
    print('Нет')'''
question2 ='''<em>Что выведет данный код:</em>
a = 5
a = a + 5
print(a)'''
question3 ='''<em>Что выведет данный код:</em>
elem = [ 34, 45, True, -8 , 256.89 ]
print(elem[1])'''
question4 ='''<em>Что выведет данный код:</em>
print( ((5 > 4) == False) or (35%5 == 0 and True) + 1 )'''
question5 ='''<em>Что выведет данный код:</em>
x = 0
while True:
    if x == 4:
        continue
    elif x > 3:
        break
    x+=1
print(x)'''
